on:
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch:

jobs:
  Build:
    environment: Development
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_DOMAIN }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set Image Tags
        id: vars
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "TAG_NAME=prod" >> $GITHUB_ENV
          else
            echo "TAG_NAME=${{ github.ref_name }}-latest" >> $GITHUB_ENV
          fi
          echo "SHA_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_DOMAIN }}/${{ secrets.REGISTRY_REPO }}:$SHA_TAG \
                       -t ${{ secrets.REGISTRY_DOMAIN }}/${{ secrets.REGISTRY_REPO }}:$TAG_NAME .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.REGISTRY_DOMAIN }}/${{ secrets.REGISTRY_REPO }}:$SHA_TAG
          docker push ${{ secrets.REGISTRY_DOMAIN }}/${{ secrets.REGISTRY_REPO }}:$TAG_NAME
